### ISSUE TITLE
Tag name error

### ISSUE THREAD

**Issue by k8s-practice** [rookie-ninja/rk-entry#31]
https://github.com/rookie-ninja/rk-entry/blob/5c70a06532c9a6454dedbf328ef30d1e0e425a97/entry/model.go#L39

**Comment by dongxuny** [comment]
A bug absolutely, will fix it

**Comment by dongxuny** [comment]
Newest version of rk-entry/v2 fixed the bug.

**Comment by dongxuny** [comment]
Closing this issue.
