### ISSUE TITLE
Is there anyway to view swagger docs offline?

### ISSUE THREAD

**Issue by emilebui** [rookie-ninja/rk-entry#69]
In the `assets/sw/index.html` file, there are some import code like this 

![image](https://user-images.githubusercontent.com/33470772/201000689-03ea99dc-5269-4b2c-9add-21fca6611522.png)

This made swagger doc requires internet to be visible as it needs to download those .js packages. Do you have any plan support offline mode?

Thank you

**Comment by dongxuny** [comment]
@emilebui Good suggestion, I think it will be good to make those js files embed. I will make a change on that. Thanks

**Comment by dongxuny** [comment]
@emilebui The newest version to rk-xxx fix this issues.
